config:
  credentials: []
  project_repos:
    github.com/Deltares-research/FloodAdapt:
      branch: main
      repo: https://github.com/Deltares-research/FloodAdapt
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/Deltares-research/FloodAdapt git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-heliotrope-maltese.sh
        container: qc.acc_hilly-lemon-ragdoll
  QC.Doc:
    repos:
      github.com/Deltares-research/FloodAdapt find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-chocolate-whippet.sh
        container: qc.doc_bluesy-alizarin-dolphin
      github.com/Deltares-research/FloodAdapt git:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-rose-fowl.sh
        container: qc.doc_pretty-charcoal-seal
      github.com/Deltares-research/FloodAdapt markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-xanthic-spider.sh
        container: qc.doc_sloppy-tomato-hippopotamus
  QC.Lic:
    repos:
      github.com/Deltares-research/FloodAdapt licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-jade-lion.sh
        container: qc.lic_stuffy-viridian-wasp
  QC.Sec:
    repos:
      github.com/Deltares-research/FloodAdapt bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-apricot-barnacle.sh
        container: qc.sec_stinky-blue-frigatebird
  QC.Sty:
    repos:
      github.com/Deltares-research/FloodAdapt flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-sepia-hare.sh
        container: qc.sty_skanky-seashell-boar
      github.com/Deltares-research/FloodAdapt jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-gold-eagle.sh
        container: qc.sty_flabby-red-fly
  QC.Uni:
    repos:
      github.com/Deltares-research/FloodAdapt pytest:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-auburn-cougar.sh
        container: qc.uni_pokey-brass-avocet
  QC.Ver:
    repos:
      github.com/Deltares-research/FloodAdapt get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-brown-akbash.sh
        container: qc.ver_bluesy-cerulean-emu
timeout: 5400
